"$schema" = "https://starship.rs/config-schema.json"

format = """
[╭─](fg:#0077C2)$shell$username\
  [](fg:#0077C2 bg:#666666)$directory\
  [](fg:#666666)\
  ([\b](fg:#666666 bg:#FFFB36)$git_branch\
   [](fg:#FFFB35))
[╰─](fg:#21C7C7)$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[❯](#E0F8FF)"
error_symbol   = "[❯](#EF5350)"

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = "[$user ]($style)"
disabled = true

[shell]
disabled = false
style = "bg:#0077C2 fg:#FFFFFF"
format = "[ ](bg:#0077C2 fg:#26C6DA)[PS ]($style)"

[directory]
style = "bg:#666666 fg:#F4F4F4"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#FFFB38 fg:#011627"
format = "[ $symbol $branch ]($style)"


[git_status]
style = "bg:#FFFB38 fg:#011627"
format = "[$all_status$ahead_behind ]($style)"
disabled = true

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = "[ $time ]($style)"
